json.id players_character.player_id
json.playername players_character.player.playername
json.character_name players_character.character.character_name
json.character_role players_character.character.character_role
